# Loki 데이터소스 자동 등록
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: "trace_id=([\\w]+)"
          url: "http://localhost:16686/trace/$${__value.raw}"
          datasourceUid: jaeger
    editable: true
    
  - name: Loki-Direct
    type: loki
    access: direct
    url: http://localhost:3100
    isDefault: false
    jsonData:
      maxLines: 5000
    editable: true
